name: GCloud Connection Test
on:
  workflow_dispatch:  # Permite execução manual apenas

jobs:
  test-gcloud-connection:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: exam-wise-app-1
      SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    
    steps:
      - name: Configurar Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      
      - name: Instalar gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Verificar autenticação e projeto
        run: |
          echo "Verificando autenticação..."
          gcloud auth list
          
          echo "Verificando projeto configurado..."
          gcloud config get-value project
      
      - name: Listar buckets de Storage
        run: |
          echo "Listando buckets de Storage disponíveis..."
          gsutil ls
      
      - name: Verificar informações do Firestore
        run: |
          echo "Verificando configuração do Firestore..."
          gcloud firestore databases list --project=${{ env.PROJECT_ID }}
      
      - name: Verificar permissões do Service Account
        run: |
          echo "Verificando permissões do Service Account..."
          PROJECT_NUMBER=$(gcloud projects describe ${{ env.PROJECT_ID }} --format="value(projectNumber)")
          SA_EMAIL=$(gcloud config get-value core/account)
          echo "Service Account: $SA_EMAIL"
          echo "Roles atribuídos:"
          gcloud projects get-iam-policy ${{ env.PROJECT_ID }} \
            --format="table(bindings.members,bindings.role)" \
            --flatten="bindings[].members" \
            | grep -i $SA_EMAIL || echo "Nenhuma permissão encontrada para este service account"
      
      - name: Resumo de verificação
        run: |
          echo "✅ Teste de conexão com Google Cloud finalizado"
          echo "📋 Resultado:"
          echo "- Autenticação: OK"
          echo "- Projeto configurado: ${{ env.PROJECT_ID }}"
          echo "- Acesso ao Storage: Verificado"
          echo "- Acesso ao Firestore: Verificado"
          echo "- Verificação de permissões: Concluída"